extends Node

enum HeldItemType { INGREDIENT, INGREDIENT_PREPARED, POT, DISH}

enum UtensilType { SUBMIT, CHOP, SCRAPE, MILL, SINK_RUNNING, SINK, OVEN, OVER_ROAST, OVEN_COOK, OVEN_BOTH }
enum Ingredient { CARROT, ONION, POTATO, TOMATO, RICE, BEANS, BEEF, CHICKEN }
enum IngredientPrepared { SCRAPED_CARROT, CHOPPED_CARROT, SCRAPED_ONION, CHOPPED_ONION, SCRAPED_POTATO, CHOPPED_POTATO,
                          CHOPPED_TOMATO, MILLED_TOMATO, NOODLES, COOKED_NOODLES, TOMATO_PASTE, ROASTED_POTATO, ROASTED_BEEF}
enum Pot { EMPTY, WATER, WATER_BOILING, NOODLES, NOODLES_BOILING, TOMATO_PASTE, TOMATO_PASTE_BOILING,
           CARROTS, CARROTS_ONIONS, CARROTS_ONIONS_CHICKEN, CHICKEN_BROTH_BOILING, CHICKEN_BROTH_NOODLES,
           CHICKEN_BROTH_TOMATO_PASTE, TOMATO_SOUP_BOILING, TOMATO_SOUP_NOODLES,
           RICE, RICE_BEANS, RICE_BEANS_BOILING}
enum Dish { BEANS_RICE, CHICKEN_BROTH_NOODLES, BEEF_POTATOES, TOMATO_SOUP_NOODLES }


class Ingredient_:
    var name