extends Node

enum HeldItemType { INGREDIENT, INGREDIENT_PREPARED, POT, DISH}

enum UtensilType { SUBMIT, CHOP, SCRAPE, MILL, SINK_RUNNING, SINK, OVEN, OVER_ROAST, OVEN_COOK, OVEN_BOTH }
enum Ingredient { CARROT, ONION, POTATO, TOMATO, RICE, BEANS, BEEF, CHICKEN }
enum IngredientPrepared { SCRAPED_CARROT, CHOPPED_CARROT, SCRAPED_ONION, CHOPPED_ONION, SCRAPED_POTATO, CHOPPED_POTATO,
                          CHOPPED_TOMATO, MILLED_TOMATO, NOODLES, COOKED_NOODLES, TOMATO_PASTE, ROASTED_POTATO, ROASTED_BEEF}
enum Pot { EMPTY, WATER, WATER_BOILING, NOODLES, NOODLES_BOILING, TOMATO_PASTE, TOMATO_PASTE_BOILING,
           CARROTS, CARROTS_ONIONS, CARROTS_ONIONS_CHICKEN, CHICKEN_BROTH_BOILING, CHICKEN_BROTH_NOODLES,
           CHICKEN_BROTH_TOMATO_PASTE, TOMATO_SOUP_BOILING, TOMATO_SOUP_NOODLES,
           RICE, RICE_BEANS, RICE_BEANS_BOILING}
enum Dish { BEANS_RICE, CHICKEN_SOUP, BEEF_POTATOES, TOMATO_SOUP }

var times = {
    Dish.BEANS_RICE: 12,
    Dish.BEEF_POTATOES: 16,
    Dish.CHICKEN_SOUP: 24,
    Dish.TOMATO_SOUP: 34,
}

var first_goals = [
    { Dish.BEANS_RICE: 2, Dish.CHICKEN_SOUP: 0, Dish.BEEF_POTATOES: 0, Dish.TOMATO_SOUP: 0 }, # 2
    { Dish.BEANS_RICE: 1, Dish.CHICKEN_SOUP: 0, Dish.BEEF_POTATOES: 2, Dish.TOMATO_SOUP: 0 }, # 3
    { Dish.BEANS_RICE: 2, Dish.CHICKEN_SOUP: 1, Dish.BEEF_POTATOES: 2, Dish.TOMATO_SOUP: 0 }, # 5
    { Dish.BEANS_RICE: 0, Dish.CHICKEN_SOUP: 3, Dish.BEEF_POTATOES: 3, Dish.TOMATO_SOUP: 0 }, # 6
    { Dish.BEANS_RICE: 2, Dish.CHICKEN_SOUP: 0, Dish.BEEF_POTATOES: 2, Dish.TOMATO_SOUP: 1 }, # 5
    { Dish.BEANS_RICE: 4, Dish.CHICKEN_SOUP: 2, Dish.BEEF_POTATOES: 2, Dish.TOMATO_SOUP: 0 }, # 8
    { Dish.BEANS_RICE: 4, Dish.CHICKEN_SOUP: 2, Dish.BEEF_POTATOES: 4, Dish.TOMATO_SOUP: 2 }, # 12
]
